<a href="https://colab.research.google.com/github/KiruthigaBalendran/Breast-Cancer-Classification/blob/main/KNN%2CNB%2CLVQ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
!pip install neupy
import pandas as pd
import numpy as np

# data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# machine learning
from sklearn.preprocessing import StandardScaler

import sklearn.linear_model as skl_lm
from sklearn.preprocessing import LabelEncoder
from sklearn import neighbors
from sklearn.metrics import confusion_matrix, classification_report, precision_score, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from neupy import algorithms, utils

# package settings initialization
sns.set(style="whitegrid", color_codes=True, font_scale=1.3)

%matplotlib inline

# Read the Data

In [51]:
# read the data and check the first 5 rows
df = pd.read_csv('/content/drive/MyDrive/MSc/Semester-4/Pattern-Recognition/Assignments/KNN/data.csv', index_col=0)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
id                                                                         
842302           M        17.99         10.38          122.80     1001.0   
842517           M        20.57         17.77          132.90     1326.0   
84300903         M        19.69         21.25          130.00     1203.0   
84348301         M        11.42         20.38           77.58      386.1   
84358402         M        20.29         14.34          135.10     1297.0   

          smoothness_mean  compactness_mean  concavity_mean  \
id                                                            
842302            0.11840           0.27760          0.3001   
842517            0.08474           0.07864          0.0869   
84300903          0.10960           0.15990          0.1974   
84348301          0.14250           0.28390          0.2414   
84358402          0.10030           0.13280          0.1980   

          concave points_mean  symmetry_mean  ...  texture_worst  \
id                                            ...                  
842302                0.14710         0.2419  ...          17.33   
842517                0.07017         0.1812  ...          23.41   
84300903              0.12790         0.2069  ...          25.53   
84348301              0.10520         0.2597  ...          26.50   
84358402              0.10430         0.1809  ...          16.67   

          perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
id                                                                           
842302             184.60      2019.0            0.1622             0.6656   
842517             158.80      1956.0            0.1238             0.1866   
84300903           152.50      1709.0            0.1444             0.4245   
84348301            98.87       567.7            0.2098             0.8663   
84358402           152.20      1575.0            0.1374             0.2050   

          concavity_worst  concave points_worst  symmetry_worst  \
id                                                                
842302             0.7119                0.2654          0.4601   
842517             0.2416                0.1860          0.2750   
84300903           0.4504                0.2430          0.3613   
84348301           0.6869                0.2575          0.6638   
84358402           0.4000                0.1625          0.2364   

          fractal_dimension_worst  Unnamed: 32  
id                                              
842302                    0.11890          NaN  
842517                    0.08902          NaN  
84300903                  0.08758          NaN  
84348301                  0.17300          NaN  
84358402                  0.07678          NaN  

[5 rows x 32 columns]

# Data Summary

In [52]:
# general summary of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 569 entries, 842302 to 92751
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se            

# Pre-processing

In [53]:
# There aren't any missing values except the column Unnamed: 32. So this column can be removed
df = df.drop('Unnamed: 32', axis=1)
df1= df

In [54]:
# Using Labelencoder to transform diagnosis characters to digits
labelencoder = LabelEncoder()
df['diagnosis'] = labelencoder.fit_transform(df['diagnosis'])
X = df
y = df['diagnosis']


# Split the data into training and testing sets
# The paper has split the data as 65.10% as training and 34.90% as testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.349, random_state=40)

# KNN Model

In [55]:
# Creating the model using n=3
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

KNeighborsClassifier()

# KNN Model Prediction

In [56]:
knn_predictions = knn_model.predict(X_test)

# KNN Accuracy 

In [57]:
# Use score method to get accuracy of model
knn_score = knn_model.score(X_test, y_test)
print("Accuracy KNN classifier : " + str(knn_score))


Accuracy KNN classifier : 0.9396984924623115


# KNN Classification Report and Confusion Matrix

In [58]:
print(classification_report(y_test, knn_predictions, digits=3))
knn_cm = confusion_matrix(y_test, knn_predictions)
print(knn_cm)

              precision    recall  f1-score   support

           0      0.942     0.970     0.956       133
           1      0.935     0.879     0.906        66

    accuracy                          0.940       199
   macro avg      0.939     0.924     0.931       199
weighted avg      0.940     0.940     0.939       199

[[129   4]
 [  8  58]]


# NB Model

In [59]:
#Create a Gaussian Classifier
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

GaussianNB()

# NB Model Prediction

In [60]:
nb_predictions = nb_model.predict(X_test)

#NB Accuracy

In [61]:
# Use score method to get accuracy of model
nb_score = nb_model.score(X_test, y_test)
print("Accuracy NB classifier : " + str(nb_score))

Accuracy NB classifier : 1.0


# NB Classification Report and Confusion Matrix

In [62]:
print(classification_report(y_test, nb_predictions, digits=3))
nb_cm = confusion_matrix(y_test, nb_predictions)
print(nb_cm)

              precision    recall  f1-score   support

           0      1.000     1.000     1.000       133
           1      1.000     1.000     1.000        66

    accuracy                          1.000       199
   macro avg      1.000     1.000     1.000       199
weighted avg      1.000     1.000     1.000       199

[[133   0]
 [  0  66]]


# LVQ Model

In [63]:
lvq_model =  algorithms.LVQ(n_inputs=9,n_subclasses=20,n_classes=2,verbose=True,show_epoch=100,step =0.0000001,n_updates_to_stepdrop=150 * 100)
lvq_model.train(X_train, y_train, epochs=2000)



Main information

[ALGORITHM] LVQ

[OPTION] minstep = 1e-05
[OPTION] n_classes = 2
[OPTION] n_inputs = 9
[OPTION] n_subclasses = 20
[OPTION] n_updates_to_stepdrop = 15000
[OPTION] prototypes_per_class = None
[OPTION] show_epoch = 100
[OPTION] shuffle_data = False
[OPTION] signals = None
[OPTION] step = 1e-07
[OPTION] verbose = True
[OPTION] weight = None

#1 : [30 ms] train: 0.081081


#100 : [20 ms] train: 0.078378


#200 : [17 ms] train: 0.078378


#300 : [33 ms] train: 0.075676


#400 : [37 ms] train: 0.070270


#500 : [75 ms] train: 0.067568


#600 : [29 ms] train: 0.059459


#700 : [84 ms] train: 0.056757


#800 : [27 ms] train: 0.054054


#900 : [27 ms] train: 0.056757


#1000 : [17 ms] train: 0.056757


#1100 : [17 ms] train: 0.056757


#1200 : [17 ms] train: 0.056757


#1300 : [17 ms] train: 0.056757


#1400 : [25 ms] train: 0.056757


#1500 : [17 ms] train: 0.054054


#1600 : [21 ms] train: 0.054054


#1700 : [17 ms] train: 0.054054


#1800 : [21 ms] train: 0.054054


#1900 : [17 ms] train: 0.048649


#2000 : [25 ms] train: 0.051351


# LVQ Model Prediction

In [64]:
lvq_predictions = lvq_model.predict(X_test)

#LVQ Accuracy

In [65]:
# Use score method to get accuracy of model
lvq_score = accuracy_score(y_test, lvq_predictions)
print("Accuracy LVQ classifier : " + str(lvq_score))

Accuracy LVQ classifier : 0.9396984924623115


# LVQ Classification Report and Confusion Matrix

In [66]:
print(classification_report(y_test, lvq_predictions, digits=3))
lvq_cm = confusion_matrix(y_test, lvq_predictions)
print(lvq_cm)

              precision    recall  f1-score   support

           0      0.942     0.970     0.956       133
           1      0.935     0.879     0.906        66

    accuracy                          0.940       199
   macro avg      0.939     0.924     0.931       199
weighted avg      0.940     0.940     0.939       199

[[129   4]
 [  8  58]]
